version: '3.7'
services:
  web:
    volumes:
      - ./services/web:/app
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: "development"
    command: python3 /app/app.py

  frontend:
    volumes:
      - ./services/frontend:/opt/app
    command: sh -c "yarn && yarn start"
    
volumes:
  pgadmin-data: